### ISSUE TITLE
respect packages_path

### ISSUE THREAD

**Issue by edmondeng** [mottosso/rez-pipz#29]
This is posed more of a question in case I really overlooked something obvious.. 

I had just setup "myrezconfig.py" to point my installed to particular locaitons unless I am in somemode set by an env variable. 

This performs as expected with  rez-build -i but with rez pipz example its pointing to /home/$USER/packages .. is rez pipz known to be  respecting these settings?

Thanks.. 
Edmond.

**Comment by mottosso** [comment]
Hi @edmondeng, could you be more specific? How can I reproduce this problem on my machine? What is `myrezconfig.py`? And what's inside of it?

**Comment by edmondeng** [comment]
Hang on I have had trouble replying from the iPhone .. will give detail

**Comment by edmondeng** [comment]
Ok.

I have the following working as advertised under regualr rez:
https://github.com/nerdvegas/rez/wiki/Configuring-Rez#cache_package_files

When I expect rez-pipz to follow suit it tells me its going to put my package here:
Packages will be installed to /home/edmond/packages
After this operation, 3.92 mb will be used.
Do you want to continue? [Y/n] n

Yet my packages path under rez installed in a custom location. Are you aware of this functionality? And is there package location control.

Please forgive me if you have this documented /

**Comment by mottosso** [comment]
Have a closer look at the Rez docs, `packages_path` isn't where packages are installed, it's where they are discovered when you call `rez env`.

To control where packages are installed, use `rez env pipz -- install my_package --prefix /my/install/path`.

**Comment by edmondeng** [comment]
Ok great I knew I had to be doing something wrong

**Comment by mottosso** [comment]
There's `local_packages_path` which is where packages are installed when using Rez, I suspect `pipz` does so too but would need to double check.

Any more trouble, feel free to re-open this issue.
