### ISSUE TITLE
Allow other package to cherry-pick specific package's python path

### ISSUE THREAD

**Issue by davidlatwe** [mottosso/rez-pipz#34]
What do you think about implementing a mechanism that will allow other package to ask `pipz` installed one to provide the module path it ships for other to use ?

Like, for example, asking `pymongo` module's path:

```python
# in other package.py which requires `pymongo`

def pre_commands():
    # asking in *pre* commands
    import os
    os.environ["PIPZ_PYMONGO_PATH"] = "-"

```

```python
# in `pipz` installed package.py

def commands():
    import os
    env.PATH.prepend('{root}/bin')
    env.PYTHONPATH.prepend('{root}/python')
    if os.getenv("PIPZ_PYMONGO_PATH"):
        env.PIPZ_PYMONGO_PATH = '{root}/python'

```

Here's my use case.

I have implemented a Rez repository plugin that requires to connect MongoDB with `pymongo` module, but the plugin could not be loaded since Rez runs in it's own environment which won't have resolved `pymongo` in it's `sys.path`.

Current solution that other uses in production is to install `pymongo` inside Rez's virtual env, but I thought maybe I could some how make my custom plugin be battery-included without touching Rez's environment.

And some where in my plugin would import `pymongo` like this:
```python
try:
    from pymongo import MongoClient
except ImportError:
    if "PIPZ_PYMONGO_PATH" in os.environ:
        sys.path.append(os.environ["PIPZ_PYMONGO_PATH"])
    from pymongo import MongoClient
```

Please let me know what you think, thanks :)

**Comment by mottosso** [comment]
> Current solution that other uses in production is to install pymongo inside Rez's virtual env

What's wrong with that though? :O Isn't that working as intended?

**Comment by davidlatwe** [comment]
Yeah, but then I would need to maintain two `pymongo` module. Just thinking that maybe I could just using one. :P
Since that custom plugin is also another Rez package and if it's not presented, Rez itself won't need `pymongo`.

**Comment by davidlatwe** [comment]
Hmmm, but yes, it's an edge case though.
And indeed it's totally fine and maybe safer to maintain in both place. 🤔

**Comment by mottosso** [comment]
Do you mean you need PyMongo in order to call Rez in the first place, for use with the repository plug-in?

I know the vanilla-Rez folks have tried Mongo for a repository in the past, maybe worth checking in and see whether they have any advice. If it were me, I would probably just vendor pymongo with your plug-in? Isn't that what we're doing with Avalon?

But yeah, it sounds really really specific and probably not worth a unique feature for.

**Comment by davidlatwe** [comment]
> Do you mean you need PyMongo in order to call Rez in the first place, for use with the repository plug-in?

Yeah ☺️

I have seen that MongoDB repository implementation PR, my plugin was based on that :P

> If it were me, I would probably just vendor pymongo with your plug-in? Isn't that what we're doing with Avalon?

Oh yes ! Hmmm, I think I'll go with installing pymongo in Rez's virtual env this time. 😁 


> maybe worth checking in and see whether they have any advice.

I did ask a few questions and this one in Rez's slack channel :P

Anyway, I'll close this issue now 🚀

Speaking of which, this plugin is for our use of Allzpark with Avalon's projects and more, will make it public soon!
