### ISSUE TITLE
Support for Scripts

### ISSUE THREAD

**Issue by mottosso** [mottosso/rez-pipz#4]
Scripts provided by Python packages are currently ignored, such as `pip.exe` from the `pip` package, or `black.exe` from `black`.

Typically, binaries made using the `entry_point` feature of `setup.py` are hard-linked to whichever Python executable was used to generate them, which isn't OK in our case. It could be a `python-3` package, or a `python-2` package, or any other arbitrary version, even system-python. Whichever binary gets linked, that's the one the generated executable would use once called, regardless of which Python was requested after having been generated.

```bash
$ rez env python-3.7 rez wheel --install black
$ rez env python-2 black
> $ black
# Screw you, I'll use 3.7
```

The "binaries" we make must instead be e.g. shell scripts, that reference just `python` rather than a full path.

**Comment by mottosso** [comment]
Have a look at whether this can be solved using https://github.com/71/scoop-better-shimexe

**rez.shim**

```bash
path = c:\windows\system32\cmd.exe
args = /c python -m rez
```

By using `cmd.exe` as the executable with `python` as arguemnt, we get `python` from the current `PATH` rather than whatever was otherwise hardcoded into the executable.

**Comment by mottosso** [comment]
This now works thanks to scoop-better-shimexe.

```bash
$ rez env pipz -- install pyblish-base
$ rez env pyblish -- pyblish --version
pyblish version 1.8.0
```

On Linux, scripts are made with plain executable scripts carrying a `#!/usr/bin/env bash` shebang.

**Comment by RafaelVillar** [comment]
Hey @mottosso It seems like this was the source of the issue I was describing via rocketchat. 

Changing the _shim args to something like you referenced 

`path = c:\windows\system32\cmd.exe`
`args = /c python -m rez`

Solved the issue for the exe created for bleeding-rez.
I also found that the line endings for the .sh files in linux caused errors. But I do not know if centos 7 is just behind on the times and if this issue between LF and CRLF has been solved in later distros. Do you know?

**Comment by RafaelVillar** [comment]
https://github.com/mottosso/rez-pipz/blob/152307c63ede54ca9d71e988b53cb1200650919b/python/pipz/pip.py#L415

For reference.

**Comment by mottosso** [comment]
Thanks, for completeness the problem was this.

```bash
$ rez env bleeding_rez python-2 --isolated
You are now in a rez-configured environment.
> $ rez context
> $ Could not create process with command 'python -u -c "import rez.cli._main as m;m.run()"  context'.
```

However I'm unable to reproduce this here.

```bash
$ rez env bleeding_rez python-2 --isolated
You are now in a rez-configured environment.
> $ rez context
resolved by marcus@Fractal, on Mon Nov 16 07:03:36 2020, using Rez v2.40.4

requested packages:
bleeding_rez
python-2
~platform==windows  (implicit)
~arch==AMD64        (implicit)
~os==windows-10     (implicit)

resolved packages:
arch-AMD64           C:\Users\marcus\packages\arch\AMD64                                 (local)
bleeding_rez-2.40.3  C:\Users\marcus\packages\bleeding_rez\2.40.3                        (local)
platform-windows     C:\Users\marcus\packages\platform\windows                           (local)
python-2.7.16        C:\Users\marcus\packages\python\2.7.16\platform-windows\arch-AMD64  (local)
> $
```

> I also found that the line endings for the .sh files in linux caused errors

Let's make both of these separate issues, also don't forget to include the error message.
